export const tipoAlquiler = ['vivienda', 'comercial'];

export const tipoAjuste = [
  {
    nombre: 'semestral',
    meses: 6,
  },
  { nombre: 'anual', meses: 12 },
  { nombre: 'trimestral', meses: 3 },
  { nombre: 'cuatrimestral', meses: 4 },
];

export const promociones = [
  {
    nombre: 'Promo del mes',
    unPago: 0.15,
    tresPagos: 0.05,
    seisPagos: 0,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Renovación',
    unPago: 0.2,
    tresPagos: 0.2,
    seisPagos: 0.2,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Referido inmobiliaria',
    unPago: 0.2,
    tresPagos: 0.1,
    seisPagos: 0.05,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Anticipada',
    unPago: 0.3,
    tresPagos: 0.2,
    seisPagos: '',
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Colectividades',
    unPago: 0.2,
    tresPagos: 0.15,
    seisPagos: '',
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Embajadas y Consulados',
    unPago: 0.2,
    tresPagos: 0.15,
    seisPagos: '',
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Convenios Estudiantes',
    unPago: 0.2,
    tresPagos: 0.15,
    seisPagos: '',
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Renovación FINAER',
    unPago: 0.25,
    tresPagos: 0.15,
    seisPagos: 0.1,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'RESPALDAR || PREMIUM',
    unPago: 0.3,
    tresPagos: 0.15,
    seisPagos: 0.1,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Especial',
    unPago: 0.15,
    tresPagos: 0.05,
    seisPagos: 0,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Especial Estudiantes',
    unPago: 0.2,
    tresPagos: 0.15,
    seisPagos: 0,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Globant',
    unPago: 0.25,
    tresPagos: 0.1,
    seisPagos: 0.05,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Recupero',
    unPago: 0.3,
    tresPagos: 0.15,
    seisPagos: 0,
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Mercado Pago',
    unPago: 0.05,
    tresPagos: 0.05,
    seisPagos: 0,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Mercado Pago Especial',
    unPago: 0.05,
    tresPagos: 0.05,
    seisPagos: 0,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Mercado Pago Renovación',
    unPago: 0.2,
    tresPagos: 0.2,
    seisPagos: 0.2,
    nuevePagos: 0.2,
    docePagos: 0.2,
  },
  {
    nombre: 'Negociación 35',
    unPago: 0.35,
    tresPagos: 0.2,
    seisPagos: 0.2,
    nuevePagos: 0.2,
    docePagos: 0.2,
  },
  {
    nombre: 'Negociación 40',
    unPago: 0.4,
    tresPagos: 0.2,
    seisPagos: 0.2,
    nuevePagos: 0.2,
    docePagos: 0.2,
  },
];

export const asesores = [
  {
    nombre: 'Ana Carolina Jara Pernia',
    email: 'ana@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Angeles Torres',
    email: 'angeles@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Federico Peyras',
    email: 'federico@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Dairalys Carrero',
    email: 'daira@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Giuliana Ramirez',
    email: 'giuliana@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Josenna Di Lorenzo',
    email: 'josenna@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Marialis Fuenmayor',
    email: 'marialis@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Paz Ramos',
    email: 'paz@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Nelson Sambrano',
    email: 'nelson@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Valentina Aguilera',
    email: 'valentina@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Zahira Caffarena',
    email: 'zahira@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Anabella Maggio',
    email: 'anabella@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Gabriel Silvera',
    email: 'g.silvera@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
];
