export const tipoAlquiler = ['vivienda', 'comercial'];

export const tipoAjuste = [
  {
    nombre: 'semestral',
    meses: 6,
  },
  { nombre: 'anual', meses: 12 },
  { nombre: 'trimestral', meses: 3 },
  { nombre: 'cuatrimestral', meses: 4 },
];

export const promociones = [
  {
    nombre: 'Promo del mes',
    unPago: { efectivo: 0.2, transferencia: 0.15 },
    tresPagos: { efectivo: 0.05, transferencia: 0, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Renovación',
    unPago: { efectivo: 0.25, transferencia: 0.2 },
    tresPagos: { efectivo: 0.1, transferencia: 0.05, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Anticipada',
    unPago: { efectivo: 0.4, transferencia: 0.3 },
    tresPagos: { efectivo: 0.1, transferencia: 0.05, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Cliente FINAER',
    unPago: { efectivo: 0.25, transferencia: 0.25 },
    tresPagos: { efectivo: 0.1, transferencia: 0.1, santander: 0 },
    seisPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Cliente RESPALDAR',
    unPago: { efectivo: 0.3, transferencia: 0.3 },
    tresPagos: { efectivo: 0.1, transferencia: 0.1, santander: 0 },
    seisPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Especial',
    unPago: { efectivo: 0.15, transferencia: 0.15 },
    tresPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Locales Shopping',
    unPago: { efectivo: 0.25, transferencia: 0.25 },
    tresPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Referidos Shopping',
    unPago: { efectivo: 0.25, transferencia: 0.25 },
    tresPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Convenios Embajadas y Consulados',
    unPago: { efectivo: 0.2, transferencia: 0.2 },
    tresPagos: { efectivo: 0.15, transferencia: 0.15, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Garantía Especial Estudiantes',
    unPago: { efectivo: 0.25, transferencia: 0.25 },
    tresPagos: { efectivo: 0.2, transferencia: 0.2, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Convenios Alas, Kinesiólogos, Enfermeros, Ingenieros, Mujeres',
    unPago: { efectivo: 0.2, transferencia: 0.2 },
    tresPagos: { efectivo: 0.15, transferencia: 0.15, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Globant, Reserve',
    unPago: { efectivo: 0.25, transferencia: 0.1 },
    tresPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Techunting',
    unPago: { efectivo: 0.2, transferencia: 0.2 },
    tresPagos: { efectivo: 0.1, transferencia: 0.1, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Chango Más - Grupo CDN',
    unPago: { efectivo: 0.25, transferencia: 0.1 },
    tresPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Boca Juniors',
    unPago: { efectivo: 0.2, transferencia: 0.2 },
    tresPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'Universidad Interamericana',
    unPago: { efectivo: 0.2, transferencia: 0 },
    tresPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    seisPagos: { efectivo: 0, transferencia: 0, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
  {
    nombre: 'La Nación',
    unPago: { efectivo: 0.25, transferencia: 0 },
    tresPagos: { efectivo: 0.1, transferencia: 0.1, santander: 0 },
    seisPagos: { efectivo: 0.05, transferencia: 0.05, santander: 0 },
    transferencia: 0.05,
    nuevePagos: 0,
    docePagos: 0,
  },
];

export const asesores = [
  {
    nombre: 'Ana Carolina Jara Pernia',
    email: 'ana@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Angeles Torres',
    email: 'angeles@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Federico Peyras',
    email: 'federico@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Dairalys Carrero',
    email: 'daira@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Giuliana Ramirez',
    email: 'giuliana@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Josenna Di Lorenzo',
    email: 'josenna@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Marialis Fuenmayor',
    email: 'marialis@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Paz Ramos',
    email: 'paz@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Nelson Sambrano',
    email: 'nelson@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Valentina Aguilera',
    email: 'valentina@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Zahira Caffarena',
    email: 'zahira@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Anabella Maggio',
    email: 'anabella@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Gabriel Silvera',
    email: 'g.silvera@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Yohana Ramírez',
    email: 'yohana@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Alejandra González',
    email: 'alejandra@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Ivan Fabre',
    email: 'ivan@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Kleyder Jesús Indriago',
    email: 'kleyder@garantiaya.com.ar',
    cargo: 'Asesor Comercial',
  },
  {
    nombre: 'Gabriela Vásquez',
    email: 'gabriela@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Fernanda Monagas',
    email: 'fernanda@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Lizmar Cottua',
    email: 'lizmar@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
  {
    nombre: 'Paula Balmaceda',
    email: 'paula.balmaceda@garantiaya.com.ar',
    cargo: 'Asesora Comercial',
  },
];
